# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build and Release

on:
  push:
    branches: [ "main", "gh-actions" ]
  pull_request:
    branches: [ "main", "gh-actions" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PROJECT_NAME: PartialAnimationReplacer

jobs:
  build-skse:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@latest

    - name: Cache vcpkg packages
      uses: lukka/run-vcpkg@v11
        
    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        configurePreset: ALL
        configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE:STRING=C:/vcpkg/scripts/buildsystems/vcpkg.cmake']"

    - name: Move binaries
      run: |
        cd ${{github.workspace}}/build/ALL
        mkdir temp
        cd temp
        move ../PartialAnimationReplacer.dll
        move ../PartialAnimationReplacer.pdb
    
    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: ${{ env.PROJECT_NAME }}-DLL
        # A file, directory or wildcard pattern that describes what to upload
        path: build/ALL/temp
        # The desired behavior if no files are found using the provided path.
        retention-days: 90
        
  compose-release:
    runs-on: ubuntu-latest
    needs: [build-skse,]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download DLL
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME}}-DLL
          path: artifacts/${{ env.PROJECT_NAME }}-DLL

      - name: Copy DLL to dist
        run: cp -r artifacts/${{ env.PROJECT_NAME }}-DLL/* ${{ github.workspace }}/dist/SKSE/Plugins
        
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME}}
          path: ${{ github.workspace }}/dist
          retention-days: 90
  
